dependencies:
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: golang-example
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: node-promotion
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.46
- name: python
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- name: yuki
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
